# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d6b1c06da56627835729c8dd21abce2c3ad21aa933e39089ffb6cd296b887f7a58a10d877c53f599df82ac19f2a41edd4c3d16da0a9a58956dd63365d0ec85f

test:
  secret_key_base: bdc0f5cb9ffb68142114b2f640174a4d8acb9eb2ef46546e80287a662178b7e0449be986875fe134b8c15bdd4a5241c5212f3a5ff445228bf10c009cb319b043

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
